server:
  port: 8881
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=CTT&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 'root'
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: 39.108.48.29
    #host: 127.0.0.1
    port: 6379
    password: hiram
    timeout: 200
  thymeleaf:
    enabled: false
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
logging:
  pattern:
    console: "%boldGreen(%d{yyyy-MM-dd HH:mm:ss.SSS}) %highlight(%-5level) %cyan(%-35logger{35}) - %msg %n"
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.pms.domain
